version: '3.8'
services:
    mysql:
      image: mysql:8.0
      container_name: pedidos-mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: pedidosdb
        MYSQL_USER: pedidos
        MYSQL_PASSWORD: pedidos
      ports:
        - "3306:3306"
      volumes:
        - mysql_data:/var/lib/mysql

    mongodb:
        image: mongo:4.4  # Alterado para 4.4 para compatibilidade com a CPU
        container_name: pedidos-mongo
        ports:
          - "27017:27017"
        volumes:
          - mongo_data:/data/db

    rabbitmq:
        image: rabbitmq:3-management
        container_name: pedidos-rabbitmq
        ports:
          - "5672:5672"
          - "15672:15672"
        environment:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest

volumes:
  mysql_data:
  mongo_data:
